---
- name: HYPERVISOR update packages
  yum:
    name: '*'
    state: latest

- name: HYPERVISOR install requirements
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - gcc
    - cmake
    - python34
    - python34-setuptools
    - virt-install
    - libvirt-client
    - qemu
    - qemu-kvm
    - qemu-kvm-tools
    - qemu-img
    - selinux-policy-mls
    - setools
    - cockpit
    - cockpit-dashboard
    - rsync
    - vconfig
    - vim
    - git

- name: HYPERVISOR open firewall
  command: firewall-cmd --add-port=9090/tcp

- name: HYPERVISOR setup PIP
  command: easy_install-2.7 pip

- name: HYPERVISOR setup PIP3
  command: easy_install pip

- name: HYPERVISOR install virtualenv
  command: pip install virtualenv

- name: HYPERVISOR install virtualenv3
  command: pip3 install virtualenv

- name: HYPERVISOR install Ansible
  command: pip3 install ansible


